package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

/**
 * AirCustomer generated by hbm2java
 */
public class AirCustomer implements java.io.Serializable {

	private float custNum;
	private String custTitle;
	private String custLname;
	private String custFname;
	private String custItitial;
	private String custAddress;
	private String custCity;
	private String custState;
	private String custZip;
	private String custAreacode;
	private String custPhone;
	private Float custBalance;
	private Float custLimit;

	public AirCustomer() {
	}

	public AirCustomer(float custNum) {
		this.custNum = custNum;
	}

	public AirCustomer(float custNum, String custTitle, String custLname, String custFname, String custItitial,
			String custAddress, String custCity, String custState, String custZip, String custAreacode,
			String custPhone, Float custBalance, Float custLimit) {
		this.custNum = custNum;
		this.custTitle = custTitle;
		this.custLname = custLname;
		this.custFname = custFname;
		this.custItitial = custItitial;
		this.custAddress = custAddress;
		this.custCity = custCity;
		this.custState = custState;
		this.custZip = custZip;
		this.custAreacode = custAreacode;
		this.custPhone = custPhone;
		this.custBalance = custBalance;
		this.custLimit = custLimit;
	}

	public float getCustNum() {
		return this.custNum;
	}

	public void setCustNum(float custNum) {
		this.custNum = custNum;
	}

	public String getCustTitle() {
		return this.custTitle;
	}

	public void setCustTitle(String custTitle) {
		this.custTitle = custTitle;
	}

	public String getCustLname() {
		return this.custLname;
	}

	public void setCustLname(String custLname) {
		this.custLname = custLname;
	}

	public String getCustFname() {
		return this.custFname;
	}

	public void setCustFname(String custFname) {
		this.custFname = custFname;
	}

	public String getCustItitial() {
		return this.custItitial;
	}

	public void setCustItitial(String custItitial) {
		this.custItitial = custItitial;
	}

	public String getCustAddress() {
		return this.custAddress;
	}

	public void setCustAddress(String custAddress) {
		this.custAddress = custAddress;
	}

	public String getCustCity() {
		return this.custCity;
	}

	public void setCustCity(String custCity) {
		this.custCity = custCity;
	}

	public String getCustState() {
		return this.custState;
	}

	public void setCustState(String custState) {
		this.custState = custState;
	}

	public String getCustZip() {
		return this.custZip;
	}

	public void setCustZip(String custZip) {
		this.custZip = custZip;
	}

	public String getCustAreacode() {
		return this.custAreacode;
	}

	public void setCustAreacode(String custAreacode) {
		this.custAreacode = custAreacode;
	}

	public String getCustPhone() {
		return this.custPhone;
	}

	public void setCustPhone(String custPhone) {
		this.custPhone = custPhone;
	}

	public Float getCustBalance() {
		return this.custBalance;
	}

	public void setCustBalance(Float custBalance) {
		this.custBalance = custBalance;
	}

	public Float getCustLimit() {
		return this.custLimit;
	}

	public void setCustLimit(Float custLimit) {
		this.custLimit = custLimit;
	}

}
