package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * AirModels generated by hbm2java
 */
public class AirModels implements java.io.Serializable {

	private Long id;
	private String name;
	private String address;
	private String website;
	private String email;
	private Date createdAt;
	private Date updatedAt;

	public AirModels() {
	}

	public AirModels(String name, String email) {
		this.name = name;
		this.email = email;
	}

	public AirModels(String name, String address, String website, String email, Date createdAt, Date updatedAt) {
		this.name = name;
		this.address = address;
		this.website = website;
		this.email = email;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
