package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

/**
 * AirQualification generated by hbm2java
 */
public class AirQualification implements java.io.Serializable {

	private String qualCode;
	private String qualDescript;

	public AirQualification() {
	}

	public AirQualification(String qualCode) {
		this.qualCode = qualCode;
	}

	public AirQualification(String qualCode, String qualDescript) {
		this.qualCode = qualCode;
		this.qualDescript = qualDescript;
	}

	public String getQualCode() {
		return this.qualCode;
	}

	public void setQualCode(String qualCode) {
		this.qualCode = qualCode;
	}

	public String getQualDescript() {
		return this.qualDescript;
	}

	public void setQualDescript(String qualDescript) {
		this.qualDescript = qualDescript;
	}

}
