package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

/**
 * AirsModel generated by hbm2java
 */
public class AirsModel implements java.io.Serializable {

	private String modCode;
	private String modManufacturer;
	private String modName;
	private Float modSeats;
	private Float modChgMile;
	private Float modWaitChg;
	private Float modCruise;
	private Float modFuelHr;

	public AirsModel() {
	}

	public AirsModel(String modCode) {
		this.modCode = modCode;
	}

	public AirsModel(String modCode, String modManufacturer, String modName, Float modSeats, Float modChgMile,
			Float modWaitChg, Float modCruise, Float modFuelHr) {
		this.modCode = modCode;
		this.modManufacturer = modManufacturer;
		this.modName = modName;
		this.modSeats = modSeats;
		this.modChgMile = modChgMile;
		this.modWaitChg = modWaitChg;
		this.modCruise = modCruise;
		this.modFuelHr = modFuelHr;
	}

	public String getModCode() {
		return this.modCode;
	}

	public void setModCode(String modCode) {
		this.modCode = modCode;
	}

	public String getModManufacturer() {
		return this.modManufacturer;
	}

	public void setModManufacturer(String modManufacturer) {
		this.modManufacturer = modManufacturer;
	}

	public String getModName() {
		return this.modName;
	}

	public void setModName(String modName) {
		this.modName = modName;
	}

	public Float getModSeats() {
		return this.modSeats;
	}

	public void setModSeats(Float modSeats) {
		this.modSeats = modSeats;
	}

	public Float getModChgMile() {
		return this.modChgMile;
	}

	public void setModChgMile(Float modChgMile) {
		this.modChgMile = modChgMile;
	}

	public Float getModWaitChg() {
		return this.modWaitChg;
	}

	public void setModWaitChg(Float modWaitChg) {
		this.modWaitChg = modWaitChg;
	}

	public Float getModCruise() {
		return this.modCruise;
	}

	public void setModCruise(Float modCruise) {
		this.modCruise = modCruise;
	}

	public Float getModFuelHr() {
		return this.modFuelHr;
	}

	public void setModFuelHr(Float modFuelHr) {
		this.modFuelHr = modFuelHr;
	}

}
