package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Asuers generated by hbm2java
 */
public class Asuers implements java.io.Serializable {

	private AsuersId id;

	public Asuers() {
	}

	public Asuers(AsuersId id) {
		this.id = id;
	}

	public AsuersId getId() {
		return this.id;
	}

	public void setId(AsuersId id) {
		this.id = id;
	}

}
