package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

/**
 * CharterNextval generated by hbm2java
 */
public class CharterNextval implements java.io.Serializable {

	private Float currentCharternr;

	public CharterNextval() {
	}

	public CharterNextval(Float currentCharternr) {
		this.currentCharternr = currentCharternr;
	}

	public Float getCurrentCharternr() {
		return this.currentCharternr;
	}

	public void setCurrentCharternr(Float currentCharternr) {
		this.currentCharternr = currentCharternr;
	}

}
