package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

/**
 * CustomerNextval generated by hbm2java
 */
public class CustomerNextval implements java.io.Serializable {

	private Float currentCustnr;

	public CustomerNextval() {
	}

	public CustomerNextval(Float currentCustnr) {
		this.currentCustnr = currentCustnr;
	}

	public Float getCurrentCustnr() {
		return this.currentCustnr;
	}

	public void setCurrentCustnr(Float currentCustnr) {
		this.currentCustnr = currentCustnr;
	}

}
