package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

/**
 * EmployeeNextval generated by hbm2java
 */
public class EmployeeNextval implements java.io.Serializable {

	private Float currentEmpnr;

	public EmployeeNextval() {
	}

	public EmployeeNextval(Float currentEmpnr) {
		this.currentEmpnr = currentEmpnr;
	}

	public Float getCurrentEmpnr() {
		return this.currentEmpnr;
	}

	public void setCurrentEmpnr(Float currentEmpnr) {
		this.currentEmpnr = currentEmpnr;
	}

}
