package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

/**
 * LoginNextval generated by hbm2java
 */
public class LoginNextval implements java.io.Serializable {

	private LoginNextvalId id;

	public LoginNextval() {
	}

	public LoginNextval(LoginNextvalId id) {
		this.id = id;
	}

	public LoginNextvalId getId() {
		return this.id;
	}

	public void setId(LoginNextvalId id) {
		this.id = id;
	}

}
