package com.firsthibernate;
// Generated 02 Sep 2020 10:42:48 AM by Hibernate Tools 5.3.0.Beta2

/**
 * TransactionNextval generated by hbm2java
 */
public class TransactionNextval implements java.io.Serializable {

	private Float currentTransnr;

	public TransactionNextval() {
	}

	public TransactionNextval(Float currentTransnr) {
		this.currentTransnr = currentTransnr;
	}

	public Float getCurrentTransnr() {
		return this.currentTransnr;
	}

	public void setCurrentTransnr(Float currentTransnr) {
		this.currentTransnr = currentTransnr;
	}

}
